### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by ascott1** [18F/linkify-citations#13]
This allow others to use this a dependency and eliminate the duplicate code in repositories such as [linkify-citations-browser](https://github.com/vzvenyach/linkify-citations-browser)

**Comment by vdavez** [comment]
Great call. Adding that to the roadmap.

**Comment by vdavez** [comment]
Done! Thanks. https://www.npmjs.com/package/linkify-citations

**Comment by ascott1** [comment]
:clap:
