### ISSUE TITLE
Is it worth pulling in citation.js as a dependency?

### ISSUE THREAD

**Issue by ascott1** [18F/linkify-citations#8]
Rather than embedding the minified version of `citation.js` directly in the file, should it be pulled in as a dependency? This would require a build step, but seems cleaner option and an easier way to keep up with potential changes to `citation.js`.

**Comment by vdavez** [comment]
Hi @ascott1. So, I actually did this as part of a refactor, see https://github.com/18F/linkify-citations/blob/master/src/linkify-citations.js and https://github.com/18F/linkify-citations/blob/master/package.json#L9

**Comment by ascott1** [comment]
:clap:
